plugins:
  - uses:
    - plugin: Meniole/personal-agent-bridge@development
  # - uses:
  #   - plugin: gentlementlegen/personal-agent@development
  #   # - plugin: https://comic-bee-miserably.ngrok-free.app
  
  - uses:
#    - plugin: https://command-start-stop-develop.deno.dev
    - plugin: https://comic-bee-miserably.ngrok-free.app
      with:
       reviewDelayTolerance: "3 Days"
       taskStaleTimeoutDuration: "30 Days"
       startRequiresWallet: false
       maxConcurrentTasks:
         member: 2
         contributor: 2
       emptyWalletText: "Please set your wallet address with the /wallet command first and try again."
       rolesWithReviewAuthority:
         - "COLLABORATOR"
         - "OWNER"
         - "MEMBER"
         - "ADMIN"
       requiredLabelsToStart:
         - name: "Priority: 1 (Normal)"
           allowedRoles: ['collaborator', 'contributor']
         - name: "Priority: 2 (Medium)"
           allowedRoles: ['contributor']
         - name: "Priority: 3 (High)"
           allowedRoles: ['collaborator', 'contributor']
         - name: "Priority: 4 (Urgent)"
           allowedRoles: ['collaborator']
         - name: "Priority: 5 (Emergency)"
       taskAccessControl:
         usdPriceMax:
           collaborator: 5
           contributor: -1
